### PR TITLE
Fix compilation on TML 1.4 v2022.7.58.9

### PR DESCRIPTION
**Pull request by murfalo**
Hello Chicken-Bones,

I have just added a very quick fix that seems to fix compilation on current TML.  Things appear to function OK after very brief testing.  Very nice QOL mod, thanks :)

Thanks,
murfalo

### CODE REVIEW

**Comment by PlayfulPiano** [comment]
Hey so I just discovered this + I noticed that utility slot doesn't seem to be on the tmodloader browser? By any chance is this still like in the works and not ready for public release or is it about to be added soon?

**Comment by Chicken-Bones** [comment]
Yeah, we want to release it, but we're waiting a little on the artist to have some time! Thanks for the PR, I'll take a look at updating internally.

**Comment by PlayfulPiano** [comment]
Ah thank you! I realize now that the version of UtilitySlot I had before in 1.3 was from a different author, so thank you for continuing this for 1.4!
Hopefully you keep it pretty customizable in case people want to be less balanced with it.

**Comment by PlayfulPiano** [comment]
I am assuming though that it can't be used until the public release correct?

**Comment by murfalo** [comment]
You should be able to download the zip and compile it yourself through the tModLoader workshop.

**Comment by PlayfulPiano** [comment]
I'm not really sure how to set up a compiling (I only really go on github to report bugs or download release files). Is there a way to get a .tmod file downloaded though directly, or would it be better for me to just wait until it's in the mod browser?

**Pull request merged**
